steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/projectakhir-backend', '.' ]
    directory: 'backend' # ganti dengan direktori backend Anda

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/projectakhir-backend' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'projectakhir-backend',
      '--image', 'gcr.io/$PROJECT_ID/projectakhir-backend',
      '--region', 'us-central1', # ganti region sesuai lokasi Cloud SQL/bucket
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--add-cloudsql-instances', 'YOUR_INSTANCE_CONNECTION_NAME',
      '--set-env-vars', 'NODE_ENV=production,PORT=5000,DB_USER=...,DB_PASSWORD=...,DB_NAME=...,DB_HOST=/cloudsql/YOUR_INSTANCE_CONNECTION_NAME,DB_PORT=5432,JWT_SECRET=...,GCLOUD_PROJECT_ID=...,GCLOUD_STORAGE_BUCKET=...'
    ]
images:
  - 'gcr.io/$PROJECT_ID/projectakhir-backend'
  
options:
  logging: CLOUD_LOGGING_ONLY