steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    dir: 'frontend'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/projectakhir-frontend', '.']
    dir: 'frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/projectakhir-frontend']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'projectakhir-frontend',
      '--image', 'gcr.io/$PROJECT_ID/projectakhir-frontend',
      '--region', 'us-central1', # ganti region sesuai kebutuhan
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/projectakhir-frontend'

options:
  logging: CLOUD_LOGGING_ONLY