steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/projectakhir-backend', '.' ]
    dir: 'backend' # ganti dengan direktori backend Anda

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/projectakhir-backend' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'projectakhir-backend',
      '--image', 'gcr.io/$PROJECT_ID/projectakhir-backend',
      '--region', 'us-central1', # ganti region sesuai lokasi Cloud SQL/bucket
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--add-cloudsql-instances', 'YOUR_INSTANCE_CONNECTION_NAME',
      '--set-env-vars', 
      "ACCESS_TOKEN_SECRET=${_ACCESS_TOKEN_SECRET},REFRESH_TOKEN_SECRET=${_REFRESH_TOKEN_SECRET},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_PASSWORD=${_DB_PASSWORD},DB_USERNAME=${_DB_USERNAME}"
    ]
images:
  - 'gcr.io/$PROJECT_ID/projectakhir-backend'
  
options:
  logging: CLOUD_LOGGING_ONLY