### Tes endpoint root
GET http://localhost:5000/

### Register
POST http://localhost:5000/user/register
Content-Type: application/json

{
  "username": "contoh8",
  "password": "rahasiaa"
}

### Get semua user (GET request, jika ada endpoint)
GET http://localhost:5000/user

### Login
POST http://localhost:5000/user/login
Content-Type: application/json

{
  "username": "contoh8",
  "password": "rahasiaa"
}

### Update user (PUT)
PUT http://localhost:5000/user/1
Content-Type: application/json

{
  "username": "updateusername",
  "password": "passwordbaru"
}

### Delete user
DELETE http://localhost:5000/user/1

### Get semua movie
GET http://localhost:5000/movie
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODg2NTk0OSwiZXhwIjoxNzQ4ODY5NTQ5fQ.r_qCfF21eXmwoeOWWJRV6R64ovAHICh-MNRrGfRXbTw

### Get detail movie by id
GET http://localhost:5000/movie/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODg2NTk0OSwiZXhwIjoxNzQ4ODY5NTQ5fQ.r_qCfF21eXmwoeOWWJRV6R64ovAHICh-MNRrGfRXbTw

### Tambah movie baru
POST http://localhost:5000/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODg2NTk0OSwiZXhwIjoxNzQ4ODY5NTQ5fQ.r_qCfF21eXmwoeOWWJRV6R64ovAHICh-MNRrGfRXbTw

{
  "title": "NARUTO",
  "description": "Film tentang bokep jepang",
  "poster_url": "https://cdns.klimg.com/resized/646x323/p/headline/0000359489.jpg",
  "genre": "HORROR",
  "year": 1990
}

### Update movie (edit, misal id=1)
PUT http://localhost:5000/movie/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODg2NTk0OSwiZXhwIjoxNzQ4ODY5NTQ5fQ.r_qCfF21eXmwoeOWWJRV6R64ovAHICh-MNRrGfRXbTw

{
  "title": "Inception (Updated)",
  "description": "Film tentang petualangan kelompok",
  "poster_url": "https://example.com/poster.jpg",
  "genre": "Action",
  "year": 2010
}

### Hapus movie (misal id=1)
DELETE http://localhost:5000/movie/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODg2NTk0OSwiZXhwIjoxNzQ4ODY5NTQ5fQ.r_qCfF21eXmwoeOWWJRV6R64ovAHICh-MNRrGfRXbTw

### Cek favorite
GET http://localhost:5000/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODg2NTk0OSwiZXhwIjoxNzQ4ODY5NTQ5fQ.r_qCfF21eXmwoeOWWJRV6R64ovAHICh-MNRrGfRXbTw

### Tambah movie ke favorite
POST http://localhost:5000/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODg2NTk0OSwiZXhwIjoxNzQ4ODY5NTQ5fQ.r_qCfF21eXmwoeOWWJRV6R64ovAHICh-MNRrGfRXbTw

{
  "movieId": 16,
  "notes": "Film ini sangat seru"
}

### Update movie dari favorite
PUT http://localhost:5000/favorite/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODg2NTk0OSwiZXhwIjoxNzQ4ODY5NTQ5fQ.r_qCfF21eXmwoeOWWJRV6R64ovAHICh-MNRrGfRXbTw
Content-Type: application/json

{
  "notes": "Film ini sangat SERUU"
}

### Hapus movie dari favorite
DELETE  http://localhost:5000/favorite/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODg2NTk0OSwiZXhwIjoxNzQ4ODY5NTQ5fQ.r_qCfF21eXmwoeOWWJRV6R64ovAHICh-MNRrGfRXbTw
Content-Type: application/json

