### Tes endpoint root
GET http://localhost:5000/

### Register
POST http://localhost:5000/user/register
Content-Type: application/json

{
  "username": "contoh8",
  "password": "rahasia"
}

### Get semua user (GET request, jika ada endpoint)
GET http://localhost:5000/user

### Login
POST http://localhost:5000/user/login
Content-Type: application/json

{
  "username": "contoh8",
  "password": "rahasia"
}

### Update user (PUT)
PUT http://localhost:5000/user/1
Content-Type: application/json

{
  "username": "updateusername",
  "password": "passwordbaru"
}

### Delete user
DELETE http://localhost:5000/user/1

### Get semua movie
GET http://localhost:5000/movie
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODc4NTU5NiwiZXhwIjoxNzQ4Nzg5MTk2fQ.vdkjorzmtLQukNdtLV6druXQBDshtOe0vsF0DES8Kdk

### Get detail movie by id
GET http://localhost:5000/movie/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODc4NTU5NiwiZXhwIjoxNzQ4Nzg5MTk2fQ.vdkjorzmtLQukNdtLV6druXQBDshtOe0vsF0DES8Kdk

### Tambah movie baru
POST http://localhost:5000/movie
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODc4NTU5NiwiZXhwIjoxNzQ4Nzg5MTk2fQ.vdkjorzmtLQukNdtLV6druXQBDshtOe0vsF0DES8Kdk

{
  "title": "KIKO12",
  "description": "Film tentang petualangan kelompok",
  "poster_url": "https://example.com/poster.jpg",
  "genre": "HORROR",
  "year": 2010
}

### Update movie (edit, misal id=1)
PUT http://localhost:5000/movie/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODc4NTU5NiwiZXhwIjoxNzQ4Nzg5MTk2fQ.vdkjorzmtLQukNdtLV6druXQBDshtOe0vsF0DES8Kdk

{
  "title": "Inception (Updated)",
  "description": "Film tentang petualangan kelompok",
  "poster_url": "https://example.com/poster.jpg",
  "genre": "Action",
  "year": 2010
}

### Hapus movie (misal id=1)
DELETE http://localhost:5000/movie/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODc4NTU5NiwiZXhwIjoxNzQ4Nzg5MTk2fQ.vdkjorzmtLQukNdtLV6druXQBDshtOe0vsF0DES8Kdk

### Cek favorite
GET http://localhost:5000/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODc4NTU5NiwiZXhwIjoxNzQ4Nzg5MTk2fQ.vdkjorzmtLQukNdtLV6druXQBDshtOe0vsF0DES8Kdk

### Tambah movie ke favorite
POST http://localhost:5000/favorite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODc4NTU5NiwiZXhwIjoxNzQ4Nzg5MTk2fQ.vdkjorzmtLQukNdtLV6druXQBDshtOe0vsF0DES8Kdk

{
  "movieId": 16,
  "notes": "Film ini sangat seru"
}

### Update movie dari favorite
PUT http://localhost:5000/favorite/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODc4NTU5NiwiZXhwIjoxNzQ4Nzg5MTk2fQ.vdkjorzmtLQukNdtLV6druXQBDshtOe0vsF0DES8Kdk
Content-Type: application/json

{
  "notes": "Film ini sangat SERUU"
}

### Hapus movie dari favorite
DELETE  http://localhost:5000/favorite/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjcsInVzZXJuYW1lIjoiY29udG9oOCIsImlhdCI6MTc0ODc4NTU5NiwiZXhwIjoxNzQ4Nzg5MTk2fQ.vdkjorzmtLQukNdtLV6druXQBDshtOe0vsF0DES8Kdk
Content-Type: application/json

